server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: milovan
    password:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false